### PR TITLE
Jesus Version of Blessing

### PR DESCRIPTION
**Pull request by utf94**

### CODE REVIEW

**Comment by asadm** [comment]
I think this needs to be an additional option? Not an overwrite of the existing generic blessing.

**Comment by utf94** [comment]
yes we can add may be religion configuration

**Comment by rudimk** [comment]
Something that I probably should have included in the docs - the original idea was to keep the package as agnostic as possible. On the other hand, if it must be done, then it would be prudent to cater to every religion, and create a configurable hook that prints the appropriate blessing for a specified religion code.

**Comment by asadm** [comment]
I think it might be required as the default blessing might not be good enough for many believers. But in the end it's your call. If you decide to do it, please define a spec so others can then contribute their versions.

**Comment by rudimk** [comment]
I'm going to keep this PR open. Let's keep the conversation open, and figure out how we can build support for different religions.

**Comment by rudimk** [comment]
Going to move this to a separate issue, closing PR.

**Pull request closed without merging**
